[package]
name = "barschbot"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
bitintr = "0.3.0"
colored = "2.1.0"
piston = "1.0.0"
piston_window = "0.132.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
